### ISSUE TITLE
[REQUEST] Line art icon

### ISSUE THREAD

**Issue by astro-ray** [NicklasVraa/NovaOS_icons#1]
Is it possible to have incons with simple line art, similar to how YouTube icons look like?

Just black lines over a white background of while lines over a black background?

![Screenshot_20230720_100430_YouTube](https://github.com/NicklasVraa/NovaOS_icons/assets/69363775/5ae3c7c7-d545-427b-a2d8-08043877d505)
![Screenshot_20230720_100355_YouTube](https://github.com/NicklasVraa/NovaOS_icons/assets/69363775/a1d4d1ee-8e63-4066-bf04-22c753a5e20c)

**Comment by NicklasVraa** [comment]
If you provide me with a link to an icon pack that looks as you describe, I can recolor them into black or white for you. I will be adding the ability to separately recolor and rescale lines and fills in the near future, which would provide even more options to achieve this look.

**Comment by astro-ray** [comment]
I tried a lot to find something similar to what I would like to have, but there are no linux icon theme that matches what I want. These UI icons are the best reference I have right now

**Comment by NicklasVraa** [comment]
Added this to the plan.

**Comment by ItsTerm1n4l** [comment]
I know this issue has already been closed but are [BeautyLine](https://www.pling.com/p/1425426) icons close enough to what you want? you could then use Color-manager to recolour them to black.

**Comment by ghost** [comment]
I have myself started working on an icon pack around this idea. I used [hey-icons](https://www.pling.com/p/1330383) as a base, you can find it here: [https://github.com/proJM-Dev-team/old-gold-icons](https://github.com/proJM-Dev-team/old-gold-icons). I have finished folders but still have quite a bit of work to do. You could use [hey-icons](https://www.pling.com/p/1330383) if you don't like the look of BeautyLine.

**Comment by ItsTerm1n4l** [comment]
@proJM-Coding maybe try using https://github.com/NicklasVraa/Color-manager on the hey-icons with #cfb53b and that might get you a suitable icon set much quicker.
Looking forward to your result.

**Comment by ghost** [comment]
I did think about that but I thought I would like to make the icons myself. Thanks for the idea though
