### ISSUE TITLE
when windows 11 port

### ISSUE THREAD

**Issue by kingofcube** [NicklasVraa/NovaOS_icons#12]
please.

**Comment by NicklasVraa** [comment]
The program is written in Python using the `os` module, so it should work on anything. Have you tried it out?

**Comment by ItsTerm1n4l** [comment]
Linux uses GTK for theming and uses icon packs for displaying icons (in the file manager). `color-manager` modifies gtk themes and linux icon packs to theme Linux. Windows doesn't use GTK or Linux icon packs - they are incompatible so although you can quite possibly install `color-manager` on Windows and change some packs you download, you will not be able to use them on Windows. sorry :(

**Comment by kingofcube** [comment]
> Linux uses GTK for theming and uses icon packs for displaying icons (in the file manager). `color-manager` modifies gtk themes and linux icon packs to theme Linux. Windows doesn't use GTK or Linux icon packs - they are incompatible so although you can quite possibly install `color-manager` on Windows and change some packs you download, you will not be able to use them on Windows. sorry :(

just make one that just exports an .ico that u chose into an .ico file

**Comment by kingofcube** [comment]
> > Linux uses GTK for theming and uses icon packs for displaying icons (in the file manager). `color-manager` modifies gtk themes and linux icon packs to theme Linux. Windows doesn't use GTK or Linux icon packs - they are incompatible so although you can quite possibly install `color-manager` on Windows and change some packs you download, you will not be able to use them on Windows. sorry :(
> 
> just make one that just exports an .ico that u chose into an .ico file

also i dont care about themes, just make it change the colors of icons

**Comment by ItsTerm1n4l** [comment]
Im sorry, I don't quite understand what you want, I get that you don't care about the GTK themes, but do you just want to be able to edit Linux icon themes on Windows to then use on Linux, or edit the icon themes and then apply and use them on Windows?

**Comment by kingofcube** [comment]
> Im sorry, I don't quite understand what you want, I get that you don't care about the GTK themes, but do you just want to be able to edit Linux icon themes on Windows to then use on Linux, or edit the icon themes and then apply and use them on Windows?

nope, edit an .ico file ans then export to png, jpg, svg or ico

**Comment by ItsTerm1n4l** [comment]
Linux Icon themes are made up of svg's or png's already, if you are trying to change an individual image there are tools online to do that. see [imagegonord](https://ign.schrodinger-hat.it/).
