### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by pychopaul** [NicklasVraa/NovaOS_icons#3]
Monochrome Breeze! plz!  
dont know the hue or saturation, but similiar to the galaxy icons you did.

**Comment by NicklasVraa** [comment]
Can you provide a link to where I can download the exact version of Breeze you want? :)

**Comment by pychopaul** [comment]
https://invent.kde.org/frameworks/breeze-icons

**Comment by NicklasVraa** [comment]
Released the code, so you can create as many variations as you want :)
