### ISSUE TITLE
Issue using colour palettes in GUI version.

### ISSUE THREAD

**Issue by ItsTerm1n4l** [NicklasVraa/NovaOS_icons#9]
Hi I have just downloaded this script and when I try to modify a theme with one of the included palettes through the GUI I get an error and the palette is not included.   
This is the error.   
```
Traceback (most recent call last):
  File "/home/pi/Downloads/Color-manager/./color_manager/gui.py", line 170, in on_palette_set
    self.palette = utils.load_palette_file(palette_picker.choice)
AttributeError: module 'utils' has no attribute 'load_palette_file'
```   
I would really like to be able to use these colour palettes to modify GTK themes, so I would really appreciate help with this.   
Thanks for the awesome script!

**Comment by NicklasVraa** [comment]
I changed the name of that function and forgot to account for it in the GUI script. Will fix right away. Thanks :)

**Comment by ItsTerm1n4l** [comment]
thank you!
